### ISSUE TITLE
MetatraderSessions 'to' time is corrupted.

### ISSUE THREAD

**Issue by oleksiilogvin** [agiliumtrade-ai/metaapi-node.js-sdk#43]
Expected: '23:59:59.999'
Actual: '00:00:59.999'

```
const data = await connection.getSymbolSpecification("EURUSD");
console.log(data.tradeSessions);
{
  SUNDAY: [ { from: '00:00:00.000', to: '23:25:59.999' } ],
  MONDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  TUESDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  WEDNESDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  THURSDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  FRIDAY: [ { from: '00:05:00.000', to: '23:55:59.999' } ],
  SATURDAY: [ { from: '00:00:00.000', to: '19:55:59.999' } ]
}

```

**Comment by RomanKisilenko** [comment]
Thank you for reporting this. What type of account is this? MT4 or MT5? G1 or G2? What is your broker?

**Comment by oleksiilogvin** [comment]
> Thank you for reporting this. What type of account is this? MT4 or MT5? G1 or G2? What is your broker?

MT5, G1, Tradeview-Demo.

**Comment by oleksiilogvin** [comment]
There is also an issue when SATURDAY session is returned when it should not:
<img width="684" alt="Screenshot 2023-07-29 at 16 19 10" src="https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/assets/36164053/57645555-428e-4f9b-84d3-f92475d087ae">

```
const data = await connection.getSymbolSpecification("XAUUSD");
console.log(data.tradeSessions);
{
  MONDAY: [ { from: '01:05:00.000', to: '00:00:59.999' } ],
  TUESDAY: [ { from: '01:05:00.000', to: '00:00:59.999' } ],
  WEDNESDAY: [ { from: '01:05:00.000', to: '00:00:59.999' } ],
  THURSDAY: [ { from: '01:05:00.000', to: '00:00:59.999' } ],
  FRIDAY: [ { from: '01:05:00.000', to: '23:55:59.999' } ],
  SATURDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ]
}
```
The same account.

**Comment by RomanKisilenko** [comment]
Do you observe the same for MT4 G1 account?

**Comment by RomanKisilenko** [comment]
Please also send me your trading account id via online chat.

**Comment by RomanKisilenko** [comment]
We've fixed the issue related to invalid time period outputs (like  WEDNESDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ]).

For this broker and EURUSD symbol there are quote/trading sessions both on Saturday and Sunday which is clearly visible in the MT5 terminal. The screenshots above are captured using a different MT account or a different symbol, not the one you've mentioned above.

**Comment by oleksiilogvin** [comment]
Great job! I have created a separate ticket for "SATURDAY issue".

**Comment by oleksiilogvin** [comment]
It looks like the issue is back.

```
const data = await connection.getSymbolSpecification("EURUSD");
{
  SUNDAY: [ { from: '00:00:00.000', to: '23:25:59.999' } ],
  MONDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  TUESDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  WEDNESDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  THURSDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  FRIDAY: [ { from: '00:05:00.000', to: '23:55:59.999' } ],
  SATURDAY: [ { from: '00:00:00.000', to: '19:55:59.999' } ]
}
```
However, MT4 G1 account type works fine.

**Comment by RomanKisilenko** [comment]
Please make sure to redeploy your account first before retesting.
